[project]
name = "magic-caster-ble"
version = "0.1.1"
description = "BLE library for interacting with the HP Magic Caster Wand"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "bleak>=1.0.1",
    "bleak-retry-connector>=4.4.3"
]
